### ISSUE TITLE
Problem about dataset id of Openml

### ISSUE THREAD

**Issue by LeCongThuong** [somepago/saint#11]
Thank you for sharing your great work!
When I want to evaluate your result on all datasets that are listed on your paper, eg,  Bank, Blastchar, Arrhythmia, ..., I had a problem about your code in data_openml.py.
The id_dataset id that you listed  in the file (1487,44, ...) did not match with datasets you list on paper (bank, blastchar, ...). 
id: 1487 when I use api of opennl.datasets.get_dataset(1487), I got ozone-level-8hr dataset.
Might you give me some suggestions to evaluate your result on datasets you listed on paper.

Many thanks!

**Comment by somepago** [comment]
Hello, the code is updated for the newer version of the paper which we will update on arxiv soon. The papers listed in the older version of the paper, some of them might be available on OpenML, for others you can use the older version of the code.
