### ISSUE TITLE
Question: only continuous variables (no category)

### ISSUE THREAD

**Issue by AaronBlare** [somepago/saint#15]
Is it possible to use SAINT for the tabular data, which contains only continuous variables, without categorical?

We need to pass to SAINT model two parameters: x_categ and x_cont
Do I need to pass some torch.empy tensor as x_categ?
What to pass as "categories" parameter to the SAINT model? Empty tuple?

**Comment by somepago** [comment]
Hi, it is possible to train the model only on continuous data. Please check how the function ([link](https://github.com/somepago/saint/blob/e288e84c77a54cfd2ffb55a53678fb7cbbb16630/data_openml.py#L43)) is outputting for openml datasets- 42178 and 42724 (they have no categorical features either), you can use the same format for your dataset.
