### ISSUE TITLE
Regression Task

### ISSUE THREAD

**Issue by asadabbas09** [somepago/saint#3]
Thanks for awesome work.

I'm using a tabular dataset for a regression task. I would like to predict the last column (float values) in the picture below.

![image](https://user-images.githubusercontent.com/25729739/126742240-82b7e020-dce9-4f91-a5c8-7282530bb9e4.png)

I'm not sure how should I setup network and esp these two parameters:
```
categories = tuple(cat_dims),
num_continuous = len(con_idxs) 
```
For now I'm using 
```
con_idxs = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
```
If I change the last column values to `int` using `train[target] = train[target].astype(int)` and use the following as cat dims it starts training but I want to predict floating values.
```
cat_dims = np.append(np.array(cat_dims),np.array([50])).astype(int)
```
If I dont convert target to `int` it throws following error:

```
 return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.DoubleTensor instead (while checking arguments for embedding)
``

**Comment by asadabbas09** [comment]
I have changed few things:
```
cat_idxs = [10,11,14,15,16,17,18,19,20,21]
con_idxs = [0,1,2,3,4,5,6,7,8,9,12,13]
```
Also, Instead of changed `train[target]` to `int`, I have changed `x_categ` and `cat_mask_temp` data types to `int` in 

`embed_data_mask(x_categ, x_cont, cat_mask, con_mask,model,vision_dset=False)`

Now network seems to be learning on float predictions but I am still not sure about following line:

`cat_dims = np.append(np.array(cat_dims),np.array([50])).astype(int)`

Please let me know what do you think about these settings.

**Comment by somepago** [comment]
Hi, Sorry for the late reply. We will include the regression case in the next version. We will be releasing it soon, please stay tuned.

**Comment by somepago** [comment]
Hello, I have just pushed the latest version of the code with the regression case too. Closing this issue for now. Raise another issue if you face problems with the new version.
