### ISSUE TITLE
Handling missing values

### ISSUE THREAD

**Issue by deepneuralnetworks** [somepago/saint#4]
Hello thanks for the code and awesome works.

I read your paper impressively and have a question about the code.

In the paper, p.14 Data preprocessing, it is written to
"_Each feature (or columns) has a different missing value token to account for missing data._".

However I found that the code just fill missing values with an average value for continuous features.

I wonder the token embedding works only for categorical data.

It was very exciting to read the paper and I hope to apply the algorithm to my dataset soon!

**Comment by somepago** [comment]
Hi, we have done the task in a bit of round-about way in the code, but you can handle missing values with this [function](https://github.com/somepago/saint/blob/a55fc0ca7ee0a35cf2b88fb692f48a31034b33ef/augmentations.py#L5). Just pass a mask array where missing value locations are 0s and rest are 1s. It works for both categorical and continuous data.

**Comment by deepneuralnetworks** [comment]
Thank you for the reply. 

Closing the issue.
